# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:ci
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - type:dependency
    ignore:
      # https://github.com/MobileTeleSystems/onetl/pull/297
      - dependency-name: pyspark
        update-types: [version-update:semver-major]
      - dependency-name: pytest-asyncio
        update-types: [version-update:semver-major]
    # https://til.simonwillison.net/github/dependabot-python-setup
    groups:
      python-packages:
        patterns:
          - '*'
