name: Clickhouse Tests
on:
  workflow_call:

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  tests:
    name: Run Clickhouse tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Clickhouse
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans
          docker compose -f docker-compose.test.yml --profile clickhouse up -d db rabbitmq horizon test-clickhouse

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Worker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: mtsrus/syncmaster-worker:${{ github.sha }}
          target: test
          file: docker/Dockerfile.worker
          load: true
          cache-from: type=gha,scope=test
          cache-to: type=gha,scope=test,mode=max

      - name: Start worker
        run: |
          docker compose -f docker-compose.test.yml --profile clickhouse up -d --wait --wait-timeout 200
        env:
          WORKER_IMAGE_TAG: ${{ github.sha }}

      - name: Run Clickhouse Tests
        run: |
          docker compose -f ./docker-compose.test.yml --profile clickhouse exec -T worker coverage run -m pytest -vvv -s ./tests/test_integration -m clickhouse

      - name: Dump worker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: mtsrus/syncmaster-worker
          dest: ./logs

      # This is important, as coverage is exported after receiving SIGTERM
      - name: Shutdown
        if: always()
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans

      - name: Upload worker logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: worker-logs-clickhouse
          path: logs/*

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-clickhouse
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
