name: Dev release

on:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: '3.13'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wait-code-analysis:
    name: Dev release package
    runs-on: ubuntu-latest
    if: github.repository == 'MobileTeleSystems/syncmaster'  # prevent running on forks

    environment:
      name: test-pypi
      url: https://test.pypi.org/project/data-syncmaster/

    permissions:
      id-token: write # to auth in Test PyPI
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Generate unique version and update test version
        run: |
          poetry self add poetry-bumpversion
          poetry self install
          version=$(poetry version -s)
          poetry version "${version}.dev${GITHUB_RUN_ID}"

      - name: Fix logo in Readme
        run: |
          sed -i "s#image:: docs/#image:: https://raw.githubusercontent.com/MobileTeleSystems/syncmaster/$GITHUB_SHA/docs/#g" README.rst

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
