name: FTPS tests
on:
  workflow_call:

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  test:
    name: Run FTPS tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache jars
        uses: actions/cache@v4
        with:
          path: ./cached_jars
          key: ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-test-ftps
          restore-keys: |
            ${{ runner.os }}-python-${{ env.DEFAULT_PYTHON }}-test-ftps
            ${{ runner.os }}-python-

      - name: Build Worker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: mtsrus/syncmaster-worker:${{ github.sha }}
          target: test
          file: docker/Dockerfile.worker
          load: true
          cache-from: type=gha,scope=test
          cache-to: type=gha,scope=test,mode=max

      - name: Docker compose up
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans
          docker compose -f docker-compose.test.yml --profile ftps up -d --wait --wait-timeout 200
        env:
          WORKER_IMAGE_TAG: ${{ github.sha }}

      - name: Run FTPS Tests
        run: |
          docker compose -f ./docker-compose.test.yml --profile ftps exec -T worker coverage run -m pytest -vvv -s -m "worker and ftps"

      - name: Dump worker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: mtsrus/syncmaster-worker
          dest: ./logs

      # This is important, as coverage is exported after receiving SIGTERM
      - name: Shutdown
        if: always()
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans

      - name: Upload worker logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: worker-logs-ftps
          path: logs/*

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ftps
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
