name: PyPI release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    if: github.repository == 'MobileTeleSystems/syncmaster'  # prevent running on forks

    environment:
      name: pypi
      url: https://pypi.org/p/data-syncmaster

    permissions:
      id-token: write # to auth in PyPI
      contents: write # to create Github release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install system dependencies
        # this step is needed for successful installation of "krb5" library in python dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf gcc make libkrb5-dev

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: 'false'

      - name: Generate OpenAPI Schema
        run: |
          uv sync --frozen --extra server
          make docs-openapi

      - name: Fix logo in Readme
        run: |
          sed -i "s#image:: docs/#image:: https://raw.githubusercontent.com/MobileTeleSystems/syncmaster/$GITHUB_SHA/docs/#g" README.rst
          sed -i "s#logo_wide_red_text.svg#logo_wide.svg#g" README.rst

      - name: Patch version template
        # Due to change above, git stage area is dirty, so we need to patch the template
        run: sed -i 's#dirty_template = ".*"#dirty_template = "{tag}"#' pyproject.toml

      - name: Build package
        run: uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Generate SBOM
        run: |
          uv pip install cyclonedx-bom
          uv export --all-extras --format requirements.txt | uv run cyclonedx-py requirements - > sbom.cyclonedx.json

      - name: Get changelog
        run: |
          cat docs/changelog/$GITHUB_REF_NAME.rst > changelog.rst

      - name: Prepare rST syntax for conversion to Markdown
        run: |
          # Replace Github links from Sphinx syntax with Markdown
          sed -i -E 's/:github:issue:`(.*)`/#\1/g' changelog.rst
          sed -i -E 's/:github:pull:`(.*)`/#\1/g' changelog.rst
          sed -i -E 's/:github:user:`(.*)`/@\1/g' changelog.rst
          sed -i -E 's/:github:org:`(.*)`/@\1/g' changelog.rst

      - name: Convert rST to Markdown
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --output=changelog.md
            --from=rst
            --to=gfm
            --wrap=none
            changelog.rst

      - name: Fixing Markdown syntax after conversion
        run: |
          # Replace ``` {.python caption="abc"} with ```python caption="abc"
          sed -i -E 's/``` \{\.(.*)\}/```\1/g' changelog.md

          # Replace ``` python with ```python
          sed -i -E 's/``` (\w+)/```\1/g' changelog.md

          # Replace \# with #
          sed -i -E 's/\\#/#/g' changelog.md

      - name: Get release name
        id: release-name
        run: |
          # Release name looks like: 0.7.0 (2023-05-15)
          echo -n name= > "$GITHUB_OUTPUT"
          cat changelog.md | head -1 | sed -E "s/#+\s*//g" >> "$GITHUB_OUTPUT"

      - name: Fix headers
        run: |
          # Remove header with release name
          sed -i -e '1,2d' changelog.md

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: ${{ steps.release-name.outputs.name }}
          body_path: changelog.md
          files: |
            dist/*.tar.gz
            dist/*.whl
            docs/_static/openapi.json
            sbom.cyclonedx.json
