name: Scheduler Tests
on:
  workflow_call:

env:
  DEFAULT_PYTHON: '3.13'

jobs:
  tests:
    name: Run Scheduler tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start db & rabbitmq
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans
          docker compose -f docker-compose.test.yml --profile worker up -d db rabbitmq

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://docs.docker.com/build/ci/github-actions/cache/#local-cache
      - name: Cache Docker layers
        uses: actions/cache/restore@v5
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-worker-${{ hashFiles('docker/Dockerfile.worker', 'pyproject.toml', 'uv.lock', 'docker/download_ivy2_packages.py', 'syncmaster/worker/ivy2.py') }}
          restore-keys: |
            ${{ runner.os }}-buildx-worker-

      - name: Build Worker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: mtsrus/syncmaster-worker:${{ github.sha }}
          target: test
          file: docker/Dockerfile.worker
          load: true
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

      - name: Start worker
        run: |
          docker compose -f docker-compose.test.yml --profile worker up -d --wait --wait-timeout 200
        env:
          WORKER_IMAGE_TAG: ${{ github.sha }}

      - name: Run Scheduler Tests
        run: |
          docker compose -f ./docker-compose.test.yml --profile worker exec -T worker coverage run -m pytest "tests/test_integration/test_scheduler" -vvv -s

      - name: Dump worker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: mtsrus/syncmaster-scheduler,mtsrus/syncmaster-worker,mtsrus/horizon-backend,postgres,rabbitmq
          dest: ./logs

      # This is important, as coverage is exported after receiving SIGTERM
      - name: Shutdown
        if: always()
        run: |
          docker compose -f docker-compose.test.yml --profile all down -v --remove-orphans

      - name: Upload worker logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: worker-logs-scheduler
          path: logs/*

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-scheduler
          path: reports/*
          # https://github.com/actions/upload-artifact/issues/602
          include-hidden-files: true
